import { Roles } from "./roles";

const { ADMIN, SYSTEM_OWNER, PROJECT_OWNER, VIEWER } = Roles;

export class Permissions {
	static MENU_PROJECTS = [ADMIN, SYSTEM_OWNER, PROJECT_OWNER, VIEWER];
	static MENU_TEAM = [ADMIN, SYSTEM_OWNER];
	static MENU_TEMPLATES = [ADMIN, SYSTEM_OWNER];
	static MENU_WORKFLOW = [ADMIN, SYSTEM_OWNER, PROJECT_OWNER];

	// FOR PROJECT
	static PROJECT_CREATE = [ADMIN, SYSTEM_OWNER];
	static PROJECT_VIEW = [ADMIN, SYSTEM_OWNER, PROJECT_OWNER, VIEWER];
	static PROJECT_LIST = [ADMIN, SYSTEM_OWNER, PROJECT_OWNER, VIEWER];
	static PROJECT_EDIT = [ADMIN, SYSTEM_OWNER, PROJECT_OWNER];
	static PROJECT_DELETE = [ADMIN, SYSTEM_OWNER];
	static PROJECT_UPLOAD = [ADMIN, SYSTEM_OWNER, PROJECT_OWNER];
	static PROJECT_DOWNLOAD = [ADMIN, SYSTEM_OWNER, PROJECT_OWNER];

	// FOR COMPARE MENUS
	static COMPARE_VIEW = [ADMIN, SYSTEM_OWNER, PROJECT_OWNER, VIEWER];
	static COMPARE_EDIT = [ADMIN, SYSTEM_OWNER, PROJECT_OWNER];
	static GET_AI_SUMMARY = [ADMIN, SYSTEM_OWNER, PROJECT_OWNER, VIEWER];

	// FOR PROJECT PROFILE 
	static PROJECT_PROFILE_MEDIA = [ADMIN, SYSTEM_OWNER, PROJECT_OWNER, VIEWER];
	static PROJECT_PROFILE_CANVAS = [ADMIN, SYSTEM_OWNER, PROJECT_OWNER, VIEWER];
	static PROJECT_PROFILE_DOCUMENTS = [ADMIN, SYSTEM_OWNER, PROJECT_OWNER, VIEWER];

	// FOR MEDIA
	static MEDIA_VIEW = [ADMIN, SYSTEM_OWNER, PROJECT_OWNER, VIEWER];
	static MEDIA_DELETE = [ADMIN, SYSTEM_OWNER, PROJECT_OWNER];

	// FOR CANVAS
	static CANVAS_EDIT = [ADMIN, SYSTEM_OWNER, PROJECT_OWNER];
	static CANVAS_SHARE_LINK = [ADMIN, SYSTEM_OWNER, PROJECT_OWNER];
	static CANVAS_MIGRATE = [ADMIN, SYSTEM_OWNER, PROJECT_OWNER];

	// FOR TEMPLATE AND DOCUMENTS
	static TEMPLATE_UPLOAD = [ADMIN, SYSTEM_OWNER, PROJECT_OWNER];
	static TEMPLATE_EDIT = [ADMIN, SYSTEM_OWNER, PROJECT_OWNER];
	static TEMPLATE_DELETE = [ADMIN, SYSTEM_OWNER, PROJECT_OWNER];
	static DOCUMENT_SIGN = [ADMIN, SYSTEM_OWNER, PROJECT_OWNER];
	static DOCUMENT_MIGRATE = [ADMIN, SYSTEM_OWNER, PROJECT_OWNER];

	// FOR WORKFLOW
	static WORKFLOW_CREATE = [ADMIN, SYSTEM_OWNER, PROJECT_OWNER];
	static WORKFLOW_LIST = [ADMIN, SYSTEM_OWNER, PROJECT_OWNER, VIEWER];
	static WORKFLOW_EDIT = [ADMIN, SYSTEM_OWNER, PROJECT_OWNER];
	static WORKFLOW_DELETE = [ADMIN, SYSTEM_OWNER, PROJECT_OWNER];

}
